f = open("C:/Users/multicampus/Desktop/Projects/webengers/WebSideProject/frontend/src/components/home/BgSvg2.js", 'r')
g = open('C:/Users/multicampus/Desktop/Projects/webengers/WebSideProject/frontend/src/components/home/BgSvg2New.js', 'w')
# f = open("C:/Users/dongm/Desktop/Projects/WebSideProject/frontend/src/components/home/BgSvg2.js", 'r')
# g = open("C:/Users/dongm/Desktop/Projects/WebSideProject/frontend/src/components/home/BgSvg2New.js", 'w')
lines = f.readlines()
for line in lines:
    line = line.replace('link:hr', 'linkHr')
    line = line.replace('_x002D_', '-')
    line = line.replace('style="overflow:', 'overflow="')
    line = line.replace('style="stop-color:', 'stopColor="')
    line = line.replace('style="font-size:', 'fontSize="')
    line = line.replace('class=', 'className=')
    line = line.replace('_x5F_1_x5F_', '')
    line = line.replace('_x5F_2_x5F_', '')
    line = line.replace('_x5F_3_x5F_', '')
    line = line.replace('_x5F_4_x5F_', '')
    line = line.replace('_x5F_5_x5F_', '')
    line = line.replace('_x5F_6_x5F_', '')
    line = line.replace('_x5F_7_x5F_', '')
    line = line.replace('_x5F_8_x5F_', '')
    line = line.replace('_x5F_9_x5F_', '')
    if 'SVGID' in line:
        print('svgid included')
    elif 'clip' in line:
        print('clip included')
    else:
        line = line.replace('_1_', '')
        line = line.replace('_2_', '')
        line = line.replace('_3_', '')
        line = line.replace('_4_', '')
        line = line.replace('_5_', '')
        line = line.replace('_6_', '')
        line = line.replace('_7_', '')
        line = line.replace('_8_', '')
        line = line.replace('_9_', '')
        line = line.replace('_10_', '')
        line = line.replace('_11_', '')
        line = line.replace('_12_', '')
        line = line.replace('_13_', '')
        line = line.replace('_14_', '')
        line = line.replace('_15_', '')
    g.write(line)
f.close()
g.close()